name: Quarto Documentation

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: write  # needed for gh-pages

jobs:
  build-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install graphviz
        run: sudo apt-get install -y graphviz

      - name: Check Quarto installation
        run: |
          poetry run quarto check

      - name: Render Quarto site
        run: |
          poetry run quarto render

      # Deploy Preview for PRs
      - name: Publish PR Preview
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          destination_dir: previews/PR${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy Dev Site from master
      - name: Publish Dev Site
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          destination_dir: dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Deploy Versioned Release
      - name: Publish Versioned Site
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create 'latest' alias for version
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "Detected version: $version"
          mkdir -p ./latest
          cp -r ./_site/* ./latest/
      
      - name: Publish Versioned Site to latest
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./latest
          destination_dir: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
